spring.application.name=ProductMicroService

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

#spring.datasource.url=jdbc:postgresql://localhost:5432/webshop_db
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.username=admin
#spring.datasource.password=admin
#
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.default_schema=products
#spring.jpa.show-sql=true

server.port=8420
